version: '3.8'

services:
  shortener-app:
    image: ghcr.io/${GITHUB_ACTOR:-yusufparker}/shortenurl:latest
    container_name: nextjs-shortener
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
