name: CI/CD ShortenURL

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/yusufparker/shortenurl:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS using Native SSH
        env:
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          HOST: ${{ secrets.VPS_HOST }}
          PORT: ${{ secrets.VPS_PORT }}
          USER: ${{ secrets.VPS_USER }}
        run: |
          mkdir -p ~/.ssh

          echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat >>~/.ssh/config <<END
          Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
          END

          CLEAN_HOST=$(echo "$HOST" | tr -d '[]')

          ssh -p $PORT -i ~/.ssh/id_rsa $USER@$CLEAN_HOST "mkdir -p ~/apps/shortenurl/prisma"
          scp -P $PORT -i ~/.ssh/id_rsa docker-compose.yml $USER@$CLEAN_HOST:~/apps/shortenurl/docker-compose.yml
          scp -P $PORT -i ~/.ssh/id_rsa prisma/schema.prisma $USER@$CLEAN_HOST:~/apps/shortenurl/prisma/schema.prisma

          ssh -p $PORT -i ~/.ssh/id_rsa $USER@$CLEAN_HOST "
            cd ~/apps/shortenurl &&
            touch .env &&
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} &&
            export GITHUB_ACTOR=${{ github.actor }} &&
            docker compose pull &&
            docker compose up -d &&
            echo 'Waiting for container to start...' &&
            sleep 5 &&
            docker exec nextjs-shortener npx -y prisma db push --accept-data-loss
          "
